# Generated by Django 2.2.19 on 2022-09-02 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('prod_name', models.CharField(max_length=200)),
                ('full_prod_name', models.CharField(max_length=200)),
                ('count', models.CharField(default=1, max_length=10)),
                ('unit_storage', models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9)),
                ('cell_store', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
                ('topic_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
                'ordering': ['-pub_date'],
            },
        ),
    ]
