# Generated by Django 2.2.19 on 2022-09-05 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('prod_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('full_prod_name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('count', models.CharField(default=1, max_length=10, verbose_name='Количество')),
                ('unit_storage', models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9, verbose_name='Эквивалент')),
                ('cell_store', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место нахождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Карточку',
                'verbose_name_plural': 'Карточка',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Request_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('unit_storage', models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9, verbose_name='Единица измерения')),
                ('link', models.CharField(blank=True, choices=[('ссылка', 'Ссылка'), ('артикул', 'Артикул'), ('фирма', 'Фирма')], default='Ссылка', max_length=40, null=True, verbose_name='Ссылка')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='pass')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Карточка товара')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
            options={
                'verbose_name': 'Заявка на товар',
                'verbose_name_plural': 'Заявка на товары',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic', verbose_name='Тема проекта'),
        ),
        migrations.AddField(
            model_name='part',
            name='topic_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic', verbose_name='Тема проекта'),
        ),
    ]
