# Generated by Django 2.2.19 on 2022-09-09 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Write_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('count', models.IntegerField()),
                ('unit_storage', models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9, verbose_name='Эквивалент')),
            ],
            options={
                'verbose_name': 'Списание товара',
                'verbose_name_plural': 'Списание товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Наименование ПКИ', 'verbose_name_plural': 'Наименование ПКИ'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='email',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='request_part',
            name='user_input',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Пользовательский ввод'),
        ),
        migrations.AlterField(
            model_name='part',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='part',
            name='man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='request_part',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Наименование ПКИ'),
        ),
        migrations.AlterField(
            model_name='request_part',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request_Man'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='write_off',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Наименование ПКИ'),
        ),
        migrations.AddField(
            model_name='request_man',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic', verbose_name='Тема проекта'),
        ),
    ]
