# Generated by Django 2.2.19 on 2022-09-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('link', models.CharField(choices=[('ссылка', 'Ссылка'), ('артикул', 'Артикул'), ('фирма', 'Фирма')], default='Ссылка', max_length=40, verbose_name='Ссылка')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='pass')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic', verbose_name='Тема проекта')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Request_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('unit_storage', models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9, verbose_name='Единица измерения')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Карточка товара')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
            options={
                'verbose_name': 'Заявка на товар',
                'verbose_name_plural': 'Заявка на товары',
            },
        ),
    ]
