# Generated by Django 2.2.19 on 2022-09-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_request_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Карточки', 'verbose_name_plural': 'Карточка'},
        ),
        migrations.AlterField(
            model_name='request_part',
            name='part',
            field=models.ForeignKey(limit_choices_to={'available_in': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')}, on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Карточка товара'),
        ),
    ]
