# Generated by Django 2.2.19 on 2022-09-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_part_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_part',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='request_part',
            name='user_input',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Пользовательский ввод'),
        ),
    ]
