# Generated by Django 2.2.19 on 2022-09-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20220902_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='link',
        ),
        migrations.RemoveField(
            model_name='request',
            name='link_url',
        ),
        migrations.AddField(
            model_name='request_part',
            name='link',
            field=models.CharField(blank=True, choices=[('ссылка', 'Ссылка'), ('артикул', 'Артикул'), ('фирма', 'Фирма')], default='Ссылка', max_length=40, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='request_part',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='pass'),
        ),
        migrations.AlterField(
            model_name='request_part',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Part', verbose_name='Карточка товара'),
        ),
    ]
