# Generated by Django 2.2.19 on 2022-09-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20220902_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Карточку', 'verbose_name_plural': 'Карточка'},
        ),
    ]
