# Generated by Django 2.2.19 on 2022-09-05 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20220905_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cell_store',
            field=models.CharField(max_length=100, verbose_name='Место нахождения'),
        ),
        migrations.AlterField(
            model_name='part',
            name='count',
            field=models.CharField(default=1, max_length=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='part',
            name='full_prod_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='part',
            name='man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='part',
            name='prod_name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='part',
            name='topic_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Topic', verbose_name='Тема проекта'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit_storage',
            field=models.CharField(choices=[('кг', 'Киллограмм'), ('шт', 'Штука'), ('г', 'Грамм')], default='кг', max_length=9, verbose_name='Эквивалент'),
        ),
    ]
